import type { Metadata } from "next";
import type { ComponentType, ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";
const ReduxProviderComponent = ReduxProvider as ComponentType<{ children: ReactNode }>;
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProviderComponent>
          {children}
        </ReduxProviderComponent>
      </body>
    </html>
  );
}
